services:
  eureka-server:
    build:
      context: ./server_eureka
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    container_name: eureka-server
    networks:
      - spring-network

  gateway-service:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    container_name: gateway-service
    depends_on:
      - eureka-server
    networks:
      - spring-network

  car-service:
    build:
      context: ./car
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    container_name: car-service
    depends_on:
      - eureka-server
    networks:
      - spring-network

  client-service:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    container_name: client-service
    depends_on:
      - eureka-server
    networks:
      - spring-network

networks:
  spring-network:
    driver: bridge