# Étape 1 : Build
FROM maven:3.8.1-openjdk-17 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

# Étape 2 : Image finale
FROM openjdk:17-jdk-slim
WORKDIR /app
COPY --from=build /app/target/gateway-service.jar ./gateway-service.jar
ENTRYPOINT ["java", "-jar", "gateway-service.jar"]
