server:
  port: 8888

spring:
  application:
    name: Gateway
  cloud:
    discovery:
      enabled: true

eureka:
  instance:
    hostname: localhost

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"  # Expose tous les endpoints Actuator
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true